// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/htanos/animalia/backend-go/ent/followrelation"
	"github.com/htanos/animalia/backend-go/ent/user"
)

// FollowRelationCreate is the builder for creating a FollowRelation entity.
type FollowRelationCreate struct {
	config
	mutation *FollowRelationMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (frc *FollowRelationCreate) SetCreatedAt(t time.Time) *FollowRelationCreate {
	frc.mutation.SetCreatedAt(t)
	return frc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (frc *FollowRelationCreate) SetNillableCreatedAt(t *time.Time) *FollowRelationCreate {
	if t != nil {
		frc.SetCreatedAt(*t)
	}
	return frc
}

// SetID sets the "id" field.
func (frc *FollowRelationCreate) SetID(u uuid.UUID) *FollowRelationCreate {
	frc.mutation.SetID(u)
	return frc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (frc *FollowRelationCreate) SetNillableID(u *uuid.UUID) *FollowRelationCreate {
	if u != nil {
		frc.SetID(*u)
	}
	return frc
}

// SetFromID sets the "from" edge to the User entity by ID.
func (frc *FollowRelationCreate) SetFromID(id uuid.UUID) *FollowRelationCreate {
	frc.mutation.SetFromID(id)
	return frc
}

// SetNillableFromID sets the "from" edge to the User entity by ID if the given value is not nil.
func (frc *FollowRelationCreate) SetNillableFromID(id *uuid.UUID) *FollowRelationCreate {
	if id != nil {
		frc = frc.SetFromID(*id)
	}
	return frc
}

// SetFrom sets the "from" edge to the User entity.
func (frc *FollowRelationCreate) SetFrom(u *User) *FollowRelationCreate {
	return frc.SetFromID(u.ID)
}

// SetToID sets the "to" edge to the User entity by ID.
func (frc *FollowRelationCreate) SetToID(id uuid.UUID) *FollowRelationCreate {
	frc.mutation.SetToID(id)
	return frc
}

// SetNillableToID sets the "to" edge to the User entity by ID if the given value is not nil.
func (frc *FollowRelationCreate) SetNillableToID(id *uuid.UUID) *FollowRelationCreate {
	if id != nil {
		frc = frc.SetToID(*id)
	}
	return frc
}

// SetTo sets the "to" edge to the User entity.
func (frc *FollowRelationCreate) SetTo(u *User) *FollowRelationCreate {
	return frc.SetToID(u.ID)
}

// Mutation returns the FollowRelationMutation object of the builder.
func (frc *FollowRelationCreate) Mutation() *FollowRelationMutation {
	return frc.mutation
}

// Save creates the FollowRelation in the database.
func (frc *FollowRelationCreate) Save(ctx context.Context) (*FollowRelation, error) {
	frc.defaults()
	return withHooks(ctx, frc.sqlSave, frc.mutation, frc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (frc *FollowRelationCreate) SaveX(ctx context.Context) *FollowRelation {
	v, err := frc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (frc *FollowRelationCreate) Exec(ctx context.Context) error {
	_, err := frc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (frc *FollowRelationCreate) ExecX(ctx context.Context) {
	if err := frc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (frc *FollowRelationCreate) defaults() {
	if _, ok := frc.mutation.CreatedAt(); !ok {
		v := followrelation.DefaultCreatedAt()
		frc.mutation.SetCreatedAt(v)
	}
	if _, ok := frc.mutation.ID(); !ok {
		v := followrelation.DefaultID()
		frc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (frc *FollowRelationCreate) check() error {
	if _, ok := frc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FollowRelation.created_at"`)}
	}
	return nil
}

func (frc *FollowRelationCreate) sqlSave(ctx context.Context) (*FollowRelation, error) {
	if err := frc.check(); err != nil {
		return nil, err
	}
	_node, _spec := frc.createSpec()
	if err := sqlgraph.CreateNode(ctx, frc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	frc.mutation.id = &_node.ID
	frc.mutation.done = true
	return _node, nil
}

func (frc *FollowRelationCreate) createSpec() (*FollowRelation, *sqlgraph.CreateSpec) {
	var (
		_node = &FollowRelation{config: frc.config}
		_spec = sqlgraph.NewCreateSpec(followrelation.Table, sqlgraph.NewFieldSpec(followrelation.FieldID, field.TypeUUID))
	)
	if id, ok := frc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := frc.mutation.CreatedAt(); ok {
		_spec.SetField(followrelation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := frc.mutation.FromIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   followrelation.FromTable,
			Columns: []string{followrelation.FromColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_following = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := frc.mutation.ToIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   followrelation.ToTable,
			Columns: []string{followrelation.ToColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_followers = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FollowRelationCreateBulk is the builder for creating many FollowRelation entities in bulk.
type FollowRelationCreateBulk struct {
	config
	err      error
	builders []*FollowRelationCreate
}

// Save creates the FollowRelation entities in the database.
func (frcb *FollowRelationCreateBulk) Save(ctx context.Context) ([]*FollowRelation, error) {
	if frcb.err != nil {
		return nil, frcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(frcb.builders))
	nodes := make([]*FollowRelation, len(frcb.builders))
	mutators := make([]Mutator, len(frcb.builders))
	for i := range frcb.builders {
		func(i int, root context.Context) {
			builder := frcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FollowRelationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, frcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, frcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, frcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (frcb *FollowRelationCreateBulk) SaveX(ctx context.Context) []*FollowRelation {
	v, err := frcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (frcb *FollowRelationCreateBulk) Exec(ctx context.Context) error {
	_, err := frcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (frcb *FollowRelationCreateBulk) ExecX(ctx context.Context) {
	if err := frcb.Exec(ctx); err != nil {
		panic(err)
	}
}
